import {
    Folder,
    Star,
    Heart,
    Sparkles,
    Flame,
    Sun,
    Moon,
    Cloud,
    Zap,
    Crown,
    Gem,
    Gift,
    Coffee,
    Gamepad2,
    Music,
    Camera,
    Image,
    File,
    User,
    Users,
    PawPrint,
    Leaf,
    Sprout,
    Car,
    Plane,
    House,
    BookOpen,
    Bookmark,
    MessageCircle,
    Bot,
    Code,
    Terminal,
    Globe,
    Compass,
    Map,
    Mountain,
    Flower2,
    Snowflake,
    Rocket,
    Shield,
    KeyRound,
    Lock,
    Flag,
    Trophy,
    Lightbulb,
    Palette,
    Headphones,
    Smile,
    Ghost,
    Cat,
    Dog,
    Fish,
    Bird,
} from "@lucide/svelte";

// A stable persisted key and a small, explicitly imported icon set.
export const folderIcons = {
    folder: Folder,
    star: Star,
    heart: Heart,
    sparkles: Sparkles,
    flame: Flame,
    sun: Sun,
    moon: Moon,
    cloud: Cloud,
    zap: Zap,
    crown: Crown,
    gem: Gem,
    gift: Gift,
    coffee: Coffee,
    gamepad: Gamepad2,
    music: Music,
    camera: Camera,
    image: Image,
    file: File,
    user: User,
    users: Users,
    paw: PawPrint,
    leaf: Leaf,
    sprout: Sprout,
    car: Car,
    plane: Plane,
    house: House,
    book: BookOpen,
    bookmark: Bookmark,
    message: MessageCircle,
    bot: Bot,
    code: Code,
    terminal: Terminal,
    globe: Globe,
    compass: Compass,
    map: Map,
    mountain: Mountain,
    flower: Flower2,
    snowflake: Snowflake,
    rocket: Rocket,
    shield: Shield,
    key: KeyRound,
    lock: Lock,
    flag: Flag,
    trophy: Trophy,
    lightbulb: Lightbulb,
    palette: Palette,
    headphones: Headphones,
    smile: Smile,
    ghost: Ghost,
    cat: Cat,
    dog: Dog,
    fish: Fish,
    bird: Bird,
};

export function getFolderIcon(key?: string) {
    return folderIcons[key as keyof typeof folderIcons] ?? Folder;
}
